package io.github.haidarim.repository;

import io.github.haidarim.entity.RevokedToken;
import org.jetbrains.annotations.NotNull;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface RevokedTokenRepository extends JpaRepository<@NotNull RevokedToken, @NotNull Long> {

    // Query is generated by Spring :)
    boolean existsByJti(String jti);

    @Modifying
    @Query("DELETE FROM RevokedToken AS rt WHERE rt.expiresAt <= CURRENT_TIMESTAMP")
    int deleteExpiredTokens();
}
