/*
 * Copyright (c) 2026 Haidarim
 * All rights reserved.
 *
 * This software is proprietary and confidential.
 * Unauthorized use, copying, modification, or distribution of this
 * software, in whole or in part, is strictly prohibited without
 * prior written permission from the author.
 */

package io.github.haidarim.repository;

import io.github.haidarim.entity.RevokedToken;
import org.jetbrains.annotations.NotNull;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

public interface RevokedTokenRepository extends JpaRepository<@NotNull RevokedToken, @NotNull Long> {

    // Query is generated by Spring :)
    boolean existsByJti(String jti);

    @Modifying
    @Query("DELETE FROM RevokedToken AS rt WHERE rt.expiresAt <= CURRENT_TIMESTAMP")
    int deleteExpiredTokens();
}
