name: SONAR CI

on:
  push:
  pull_request:
jobs: 
  release: 
    uses: haidarim/ci-templates/.github/workflows/java-sonar-ci.yml@v1.1.8
    with:
      java-version: "21"
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      project-key: "jwt-auth"
      organization: "haidarim"
      

